### ISSUE TITLE
TaskStatus combination

### ISSUE THREAD

**Issue by susnicek** [leomil72/leOS#4]
Dear developer,
first of all - thank you for this useful project you are sharing with others. I would like to ask if it is possible to combine TaskStatus-es using "|" operator. For example I need to prepare onetime+paused task and after some while I want to trigger it using "restartTask" function. So, is it possible to achieve this using:
`myOS.addTask(myTask, 500, PAUSED | ONETIME);`?

Best regards, Susnicek

**Comment by leomil72** [comment]
Sorry, the library is very simple and just execute basic commands. So you can't use logic operators to get what you want.
